<?xml version="1.0" encoding="utf-8"?><Database Name="BOOKSHOPSDB" Class="BookShopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-59C9UNMJ\KI;Initial Catalog=BOOKSHOPSDB;Integrated Security=True" SettingsObjectName="BookShopManager.Properties.Settings" SettingsPropertyName="BOOKSHOPSDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BillDetailTbl" Member="BillDetailTbls">
    <Type Name="BillDetailTbl">
      <Column Name="BillDetailId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameBook" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PriceBook" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quanlity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdBill" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BillTbl_BillDetailTbl" Member="BillTbl" ThisKey="IdBill" OtherKey="BillId" Type="BillTbl" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserTbl" Member="UserTbls">
    <Type Name="UserTbl">
      <Column Name="UId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UName" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="UPhone" Type="System.String" DbType="NVarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="UAdd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UPass" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UYob" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="UType" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UAvatar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.BillTbl" Member="BillTbls">
    <Type Name="BillTbl">
      <Column Name="BillId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UName" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ClineName" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="BillTbl_BillDetailTbl" Member="BillDetailTbls" ThisKey="BillId" OtherKey="IdBill" Type="BillDetailTbl" />
    </Type>
  </Table>
  <Table Name="dbo.BookTbl" Member="BookTbls">
    <Type Name="BookTbl">
      <Column Name="BId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BTitle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BAuthor" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="BCat" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="BQty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BImage" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BPic" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="CategoryTbl_BookTbl" Member="CategoryTbl" ThisKey="BCat" OtherKey="Category" Type="CategoryTbl" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryTbl" Member="CategoryTbls">
    <Type Name="CategoryTbl">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CategoryTbl_BookTbl" Member="BookTbls" ThisKey="Category" OtherKey="BCat" Type="BookTbl" />
    </Type>
  </Table>
</Database>